name: "GitHub Action Test"
on:
  push:
    tags-ignore:
      - '**'
  pull_request:
    types: [ labeled ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: action
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      # Checkout and install prerequisites
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      # Install and run tests
      - name: Install
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm t
