name: Build and Publish to JFrog Artifactory
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Step 3: Set up JFrog CLI
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        with:
          version: '2.73.2' # Updated version
      # Step 6: Configure JFrog CLI (explicitly)
      - name: Configure JFrog CLI
        run: |
          jf c add artifactory-server \
            --url=${{ secrets.JF_URL }} \
            --access-token=${{ secrets.JF_ACCESS_TOKEN }} \
            --interactive=false
      # Step 5: Configure npm to use JFrog Artifactory
      - name: Configure npm registry
        run: |
          jf npm-config \
            --repo-resolve=git-amitesh-npm \
            --repo-deploy=git-amitesh-npm \
            --server-id-resolve=artifactory-server \
            --server-id-deploy=artifactory-server
      # Step 4: Install dependencies
      - name: Install dependencies
        run: jf npm install
      # Step 5: Run build
      - name: Build the project
        run: jf npm run build
      # Step X: Upload artifacts to GitHub
      - name: Upload build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/**/* # Path to the build artifacts      
      # Step 7: Upload build output to Artifactory
      - name: Upload build output to Artifactory
        run: |
          jf npm publish \
            --build-name=git-npm-build \
            --build-number=${{ github.run_number }} \
            --server-id=artifactory-server
      # Step 8: Publish Build Info
      - name: Publish Build Info
        run: |
          jf rt build-publish git-npm-build ${{ github.run_number }} 
